blank_issues_enabled: false
contact_links:
  - name: DLSS Unlocked NexusMods Mod Page
    url: https://www.nexusmods.com/site/mods/2264
    about: Visit the NexusMods page for guides, discussions, and updates.
